x-qdrant-config: &qdrant-config
  # Qdrant connection settings for debugging
  QDRANT_HOST: qdrant
  QDRANT_PORT: 6333
  QDRANT_GRPC_PORT: 6334
  QDRANT_API_KEY: ""  # No API key needed for local development

services:
  mcp_server_qdrant:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: mcp-server-qdrant-debug
    container_name: mcp_server_qdrant_debug
    command: [
      "python", "-m", "debugpy", "--listen", "0.0.0.0:5680",
      "-m", "mcp_server_qdrant", "--port", "8000", "--reload"
    ]
    ports:
      - "8005:8000"  # Main application port for Qdrant service
      - "5680:5680"  # debugpy port for attaching debugger
    volumes:
      - ./src/mcp_server_qdrant:/app/mcp_server_qdrant:ro
    env_file: .env
    environment: {}
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_storage
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    environment:
      <<: *qdrant-config
    restart: unless-stopped
    
volumes:
  qdrant-data: